apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    context: docker-k8s-lab
spec:
  containers:
    -
      name: mysql
      image: nixvipin/mymysql
      env:
        -
          name: "MYSQL_USER"
          value: "root"
        -
          name: "MYSQL_DATABASE"
          value: "mydb"
        -
          name: "MYSQL_ROOT_PASSWORD"
          value: "root"
      ports:
        -
          containerPort: 3306
